src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\OneToMany(mappedBy: 'categorie', targetEntity: Produit::class)]
    private Collection $produits;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    private ?Magasin $Magasin = null;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setCategorie($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getCategorie() === $this) {
                $produit->setCategorie(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return $this->nom;
    }

    public function getMagasin(): ?Magasin
    {
        return $this->Magasin;
    }

    public function setMagasin(?Magasin $Magasin): static
    {
        $this->Magasin = $Magasin;

        return $this;
    }
}

src/Entity/Entree.php
<?php

namespace App\Entity;

use App\Repository\EntreeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntreeRepository::class)]
class Entree
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $num_be = null;

    #[ORM\Column]
    private ?int $qteEntree = null;

    #[ORM\Column]
    private ?bool $transfert = null;

    #[ORM\Column(nullable: true)]
    private ?int $prix = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'entrees')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Produit $produit = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $fournisseur = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumBe(): ?int
    {
        return $this->num_be;
    }

    public function setNumBe(int $num_be): static
    {
        $this->num_be = $num_be;

        return $this;
    }

    public function getqteEntree(): ?int
    {
        return $this->qteEntree;
    }

    public function setqteEntree(int $qteEntree): static
    {
        $this->qteEntree = $qteEntree;

        return $this;
    }

    public function isTransfert(): ?bool
    {
        return $this->transfert;
    }

    public function setTransfert(bool $transfert): static
    {
        $this->transfert = $transfert;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getFournisseur(): ?string
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?string $fournisseur): static
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }
    
}

src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $num_bs = null;

    #[ORM\Column]
    private ?int $qteSortie = null;

    #[ORM\Column]
    private ?bool $transfert = null;

    #[ORM\Column(nullable: true)]
    private ?int $prix = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Produit $produit = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $destinataire = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumBs(): ?int
    {
        return $this->num_bs;
    }

    public function setNumBs(int $num_bs): static
    {
        $this->num_bs = $num_bs;

        return $this;
    }

    public function getQteSortie(): ?int
    {
        return $this->qteSortie;
    }

    public function setQteSortie(int $qteSortie): static
    {
        $this->qteSortie = $qteSortie;

        return $this;
    }

    public function isTransfert(): ?bool
    {
        return $this->transfert;
    }

    public function setTransfert(bool $transfert): static
    {
        $this->transfert = $transfert;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getDestinataire(): ?string
    {
        return $this->destinataire;
    }

    public function setDestinataire(?string $destinataire): static
    {
        $this->destinataire = $destinataire;

        return $this;
    }
}

src/Controller/PdfGeneratorController.php
<?php

namespace App\Controller;

use App\Entity\Entree;
use App\Entity\Sortie;
use App\Repository\GestionnaireRepository;
use App\Repository\MagasinRepository;
use App\Repository\ProduitRepository;
use Dompdf\Dompdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PdfGeneratorController extends AbstractController
{
    #[Route('/pdf/generator/entree/{id}', name: 'app_pdf_generator')]
    public function index(Entree $entree=null): Response
    {
        // return $this->render('pdf_generator/index.html.twig', [
        //     'controller_name' => 'PdfGeneratorController',
        // ]);
        $data = [
            // 'imageSrc'  => $this->imageToBase64($this->getParameter('kernel.project_dir') . '/public/img/profile.png'),
            'entree'         => $entree
        ];
        $html =  $this->renderView('pdf_generator/entree.html.twig', $data);
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->render();
         
        return new Response (
            $dompdf->stream('resume', ["Attachment" => false]),
            Response::HTTP_OK,
            ['Content-Type' => 'application/pdf']
        );
    }
    #[Route('/pdf/generator/sortie/{id}', name: 'app_pdf_generator_sortie')]
    public function sortie(Sortie $sortie=null): Response
    {
        // return $this->render('pdf_generator/index.html.twig', [
        //     'controller_name' => 'PdfGeneratorController',
        // ]);
        $data = [
            // 'imageSrc'  => $this->imageToBase64($this->getParameter('kernel.project_dir') . '/public/img/profile.png'),
            'sortie'         => $sortie
        ];
        $html =  $this->renderView('pdf_generator/sortie.html.twig', $data);
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->render();
         
        return new Response (
            $dompdf->stream('resume', ["Attachment" => false]),
            Response::HTTP_OK,
            ['Content-Type' => 'application/pdf']
        );
    }
    #[Route('/pdf/generator/stock', name: 'app_pdf_generator_stock')]
    public function stock(MagasinRepository $magasinRepository, ProduitRepository $produitRepository, GestionnaireRepository $gestionnaireRepository): Response
    {
        $user = $this->getUser();
        $gestionnaire = $gestionnaireRepository->findOneBy(["email" => $user->getUserIdentifier()]);
        $magasins = $magasinRepository->findBy(["gestionnaire" => $gestionnaire]);
        $produits = $produitRepository->findBy(["magasin" => $magasins[0]]);
        $stock = [];
        // dd($produits);
        foreach ($magasins as $m) {
            foreach ($produits as $p){
                if ($p->getMagasin()->getId() == $m->getId()) {
                    $stock[] = [
                        "code" => $p->getCode(),
                        "qte" => $p->getQte(),
                        "magasinid" => $p->getMagasin()->getId(),
                    ];
                }else{
                    $produit = $produitRepository->findOneBy(["code" => $p->getCode()]);
                    $stock[] = [
                        "code" => $produit->getCode(),
                        "qte" => $produit->getQte(),
                        "magasinid" => $produit->getMagasin()->getId(),
                    ];
                }
            }
        }
        $data = [
            // 'imageSrc'  => $this->imageToBase64($this->getParameter('kernel.project_dir') . '/public/img/profile.png'),
            'stock'         => $stock,
            'magasins' => $magasins,
        ];
        $html =  $this->renderView('pdf_generator/stock.html.twig', $data);
        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->render();
         
        return new Response (
            $dompdf->stream('resume', ["Attachment" => false]),
            Response::HTTP_OK,
            ['Content-Type' => 'application/pdf']
        );
    }
}

templates/pdf_generator/entree.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <title>Bon d'Entree</title>
</head>
<body>

<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h5 class="card-title text-center">Accusé de Réception du Produit</h5>
    </div>
    <div class="card-body">
      <p class="card-text">Bonjour {{entree.fournisseur}},</p>

      <p class="card-text">Nous vous informons que nous avons bien réceptionné le produit enregistré à la date du {{entree.date|date('d/m/Y')}}. Le colis a été reçu en bon état, et nous avons procédé à la vérification de son contenu.</p>

      <h6 class="card-subtitle mb-2 text-muted">Détails de la Réception :</h6>
      <ul>
        <li>Numero Bon     : {{entree.numBe}}</li>
        <li>Produit     : {{entree.produit}}</li>
        <li>Quantité    : {{entree.qteEntree}}</li>
        <li>Prix    : {{entree.prix}}</li>
        {# <li>Date        : </li> #}
      </ul>

      <p class="card-text">Nous tenons à vous assurer que nous accorderons toute l'attention nécessaire au traitement de cette réception. Si des problèmes devaient survenir ou si des éléments supplémentaires étaient nécessaires, nous ne manquerons pas de vous contacter dans les plus brefs délais.</p>

      <p class="card-text">Nous vous remercions pour la qualité du service que vous avez fourni jusqu'à présent, et restons à votre disposition pour toute question ou clarification.</p>

      <p class="card-text">Cordialement,</p>
      <p class="card-text">{{entree.produit.magasin.magasinier}}<br>Magasinier<br>{{entree.produit.magasin}}</p>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

templates/pdf_generator/sortie.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <title>Bon de Sortie</title>
</head>
<body>

<div class="container mt-5">
  <div class="card">
    <div class="card-header">
      <h5 class="card-title text-center">BON DE SORTIE</h5>
    </div>
    <div class="card-body">
      <p class="card-text">Date : {{sortie.date|date('d/m/Y')}}</p>

      <h6 class="card-subtitle mb-2 text-muted">DÉTAILS DE LA SORTIE :</h6>
      <ul>
        <li>Destinataire      : {{sortie.destinataire}}</li>
        <li>Numéro de sortie  : {{sortie.numBs}}</li>
      </ul>

      <ul>
        <li>Produit     : {{sortie.produit}}</li>
        <li>Quantité    : {{sortie.qteSortie}}</li>
        <li>Prix        : {{sortie.prix}}</li>
        {# <li>Date        : </li> #}
      </ul>

      <p class="card-text">Remarques : </p>

      <p class="card-text">Émis par :</p>
      <p class="card-text">{{sortie.produit.magasin.magasinier}}<br>Magasinier<br>{{sortie.produit.magasin}}</p>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

templates/pdf_generator/stock.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock</title>
</head>
<body>
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 20px;
    }

    h1 {
        text-align: center;
        color: #007bff; /* Couleur du texte */
    }

    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    th, td {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    th {
        background-color: #f2f2f2; /* Couleur de fond des cellules d'en-tête */
    }

    td {
        background-color: #fff; /* Couleur de fond des cellules de données */
    }

    tr:nth-child(even) {
        background-color: #f9f9f9; /* Couleur de fond des lignes paires */
    }

    tr:hover {
        background-color: #e1e1e1; /* Couleur de fond lorsqu'on survole une ligne */
    }

    td[colspan="8"] {
        font-style: italic;
        text-align: center;
    }
</style>

    <h1 align="center">Etat Global des Stocks</h1>
    <table class="table table-responsive-md">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Nom</th>
                <th>Prix</th>
                <th>Code</th>
                {% for m in magasins %}
                    <th>Qte {{ m.nom }}</th>
                {% endfor %}
                <th>Seuil</th>
                <th>Categorie</th>
                {# <th>Date</th> #}
            </tr>
        </thead>
        <tbody>
        {% for produit in magasins[0].produits %}
            <tr>
                {# <td>{{ produit.id }}</td> #}
                <td>{{ produit.nom }}</td>
                <td>{{ produit.prix }}</td>
                <td>{{ produit.code }}</td>
                {% for s in stock %}
                    <td>{{s.qte}}</td>
                {% endfor %}
                
                <td>{{ produit.seuil }}</td>
                <td>{{ produit.categorie }}</td>
                {# <td>{{ produit.date ? produit.date|date('Y-m-d') : '' }}</td> #}
            </tr>
        {% else %}
            <tr>
                <td colspan="8">Aucun produit</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</body>
</html>